# Generated by Django 2.1.5 on 2019-04-13 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
