# Generated by Django 2.1.5 on 2019-04-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20190419_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='ref_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
